const test=require('node:test'),assert=require('node:assert/strict');
const {createJournal,KEY}=require('./oracle-journal-store.js');
function memory(){const data=new Map();return {getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,v)}}
const sample={id:'reading-1',createdAt:'2026-09-23T10:00:00.000Z',cardId:17,theme:'未分類',memo:''};
test('save survives a new instance and duplicate clicks preserve one entry',()=>{const storage=memory(),a=createJournal(storage);assert.deepEqual(a.list(),[]);a.save(sample);a.save({...sample,theme:'仕事・学び'});const b=createJournal(storage);assert.equal(b.list().length,1);assert.equal(b.list()[0].theme,'未分類');assert.equal(b.list()[0].cardId,17)});
test('editing theme and memo preserves result identity and creation date',()=>{const s=memory(),j=createJournal(s);j.save(sample);const memo='<img src=x onerror=alert(1)>\n今日を振り返る';j.update(sample.id,{theme:'自分自身',memo});const r=createJournal(s).list()[0];assert.equal(r.memo,memo);assert.equal(r.theme,'自分自身');assert.equal(r.createdAt,sample.createdAt);assert.equal(r.cardId,17);assert.throws(()=>j.update('missing',{theme:'未分類',memo:''}))});
test('newest results sort first and edits from another instance are retained',()=>{const s=memory(),a=createJournal(s),b=createJournal(s);a.save(sample);b.save({...sample,id:'reading-2',createdAt:'2026-09-24T10:00:00.000Z'});a.update('reading-1',{theme:'その他',memo:'追記'});assert.deepEqual(b.list().map(r=>r.id),['reading-2','reading-1'])});
test('invalid or future data is not silently erased',()=>{for(const raw of ['{broken',JSON.stringify({version:2,entries:[]}),JSON.stringify({version:1,entries:[{...sample,cardId:99}]})]){const s=memory();s.setItem(KEY,raw);const j=createJournal(s);assert.throws(()=>j.list());assert.throws(()=>j.save(sample));assert.equal(s.getItem(KEY),raw)}});
test('quota and access failures remain failures without false save success',()=>{const j=createJournal({getItem:()=>null,setItem:()=>{throw Error('QuotaExceededError')}});assert.throws(()=>j.save(sample),/保存/);const denied=createJournal({getItem:()=>{throw Error('Denied')},setItem:()=>{}});assert.throws(()=>denied.list(),/読み込/)});
test('rejects invalid inputs and oversized memos without altering existing records',()=>{const s=memory(),j=createJournal(s);j.save(sample);assert.throws(()=>j.save({...sample,id:'bad',cardId:-1}));assert.throws(()=>j.update(sample.id,{theme:'unknown',memo:''}));assert.throws(()=>j.update(sample.id,{theme:'未分類',memo:'x'.repeat(2001)}));assert.equal(j.list()[0].memo,'')});

test('saved messages survive edits and reloads',()=>{const s=memory(),j=createJournal(s),reading={title:'当日の言葉',message:'保存時のメッセージ',action:'一歩'};j.save({...sample,reading});j.update(sample.id,{theme:'その他',memo:'後日のメモ'});assert.deepEqual(createJournal(s).list()[0].reading,reading)});

